/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef FCFFPOLICY_H
#define FCFFPOLICY_H

/* function declarations */
void init_fcFFPolicy(void);
Netsnmp_Node_Handler handle_fcFFPolicy;

#endif /* FCFFPOLICY_H */
